{% set name = "scattertext" %}
{% set version = "0.0.2.69" %}
{% set sha256 = "1d276abf2f75e1cce64b84cb8d6a9af6576d4b9bee7b2b0539dc66b484787fc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win32]
  entry_points:
    - scattertext = scattertext.CLI:main


requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - spacy
    - jieba
    - empath
    - gensim
    - future

test:
  imports:
    - scattertext
  commands:
    - scattertext -h

about:
  home: https://github.com/JasonKessler/scattertext
  license: Apache-2.0
  license_file: LICENSE
  summary: Beautiful visualizations of how language differs among document types

  description: |
    A tool for finding distinguishing terms in small-to-medium-sized corpora, and presenting them in a sexy, 
    interactive scatter plot with non-overlapping term labels. Exploratory data analysis just got more fun.
  dev_url: https://github.com/JasonKessler/scattertext

extra:
  recipe-maintainers:
    - synapticarbors
    - JasonKessler
