{% set name = "scattertext" %}
{% set version = "0.0.2.73" %}
{% set sha256 = "e2fdcab8af7cb63e286d218b99266d9fbcf0714712f6062985aab59f49f69360" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scattertext = scattertext.CLI:main


requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - six
    - mock
    - statsmodels
    - flashtext

test:
  imports:
    - scattertext
  commands:
    - scattertext -h

about:
  home: https://github.com/JasonKessler/scattertext
  license: Apache-2.0
  license_file: LICENSE
  summary: Beautiful visualizations of how language differs among document types

  description: |
    A tool for finding distinguishing terms in small-to-medium-sized corpora, and presenting them in a sexy, 
    interactive scatter plot with non-overlapping term labels. Exploratory data analysis just got more fun.
  dev_url: https://github.com/JasonKessler/scattertext

extra:
  recipe-maintainers:
    - synapticarbors
    - JasonKessler
