{% set name = "scattertext" %}
{% set version = "0.1.12" %}
{% set sha256 = "c405d524bed7969c5f99f4aef27d45a05fd84bb544f8243932dc196bd914f885" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scattertext = scattertext.CLI:main


requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - statsmodels
    - flashtext
    - gensim >=4.0
    - spacy >=3.2

test:
  imports:
    - scattertext
  requires:
    - pip
  commands:
    - scattertext -h
    - pip check

about:
  home: https://github.com/JasonKessler/scattertext
  license: Apache-2.0
  license_file: LICENSE
  summary: Beautiful visualizations of how language differs among document types

  description: |
    A tool for finding distinguishing terms in small-to-medium-sized corpora, and presenting them in a sexy, 
    interactive scatter plot with non-overlapping term labels. Exploratory data analysis just got more fun.
  dev_url: https://github.com/JasonKessler/scattertext

extra:
  recipe-maintainers:
    - synapticarbors
    - JasonKessler
