appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: auj9FkxuohhfFzCnqPSXEuvnNP9jDTsUSwqkQAax+0jkbKcBDtV/bpXvpc+cg5jxJsE4JbRaepHfbnc0SDrezIO63kW6lnmAQOFURlToeM2K6bt5guqEJJOmDbzLMQ87s9XefeSQaBTCiJcgBOUrdpSJ7peUUzMSIhxs2tG1yKhvBKHLQ4+JBEy9jsPKZsiSgNk/4E93239I00fCZX8WQBl5cdV3GXBncFBrV0KobvimaMcy8acKdfvPCqqD7Ln2+XISoPlWWMRe3g3EX5kAQEmp97pJeYYcDW5QRPPUboCGUpsKyALlkM4VOYoAsuUN89kdMkhBfJ4jXGg/xhuoJ0nLDfGcgOuDy1rW7HUI+KMrH3Q05s7Ij0JKgccvAd/mSRe/KKJ4rEJeZKHQYEmhElpGWWNIrWuul5mW4TAcdsuoTnxERUrcHHrEtGhLbGtN/P9QVZy/guCy2U3U9Njynxhpz8zYBfNeEcj0v58sT3k5FXccK0S8FYvejalnHa7es//wUpg0qrCTAIgBNB6kvW9dtoAzJXqN5yK9HHIkaDW8B/KPU6YBpbXp2OD/A9+Cq0omEXUqN3220mY9tTZFJGGZDwHlQ+8ORiWVpQU50ZjMCOX7tUw1CYrcbdEzK0JirkdGX2FxsRnac45oN9By9hcgG90AlLDWGP7vBLTIZxs=}
provider:
  win: azure
conda_forge_output_validation: true
